site:
  title: Embedded Wizard Tutorial

content:
  sources:
  - url: ./../../
    branches: HEAD
    start_path: www/asciidoc

asciidoc:
  attributes:
    experimental: true    

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./../../docs